server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_drive?useSSL=false&serverTimezone=Asia/Shanghai&useLegacyDatetimeCode=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      # 更新或者创建数据表结构
      ddl-auto: update
    # 控制台显示SQL
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 1
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2

  mail:
    # 发送者邮箱
    username: 1017666090@qq.com
    #申请到的授权码
    password: pcmtkdixwwmzbcfe
    # 配置 SMTP 服务器地址
    host: smtp.qq.com
    # 端口号465或587
    port: 465
    protocol: smtps
    # 默认的邮件编码为UTF-8
    default-encoding: UTF-8
    # 配置SSL 加密工厂
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory
          #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
          debug: true
          ssl: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true